[package]
name = "pb"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
tokio-tungstenite = "0.22"
futures-util = "0.3"
serde_json = {version="1.0.99"}
serde = "1.0.225"
actix = "0.13.5"
actix-web = "4"
actix-files = "0.6.8"
serde_with = "3.14.1"
